const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('spanishC1', {
  getAppState: () => ipcRenderer.invoke('app:get-state'),
  getBootstrapStatus: () => ipcRenderer.invoke('app:get-bootstrap-status'),
  getReadiness: () => ipcRenderer.invoke('app:get-readiness'),
  acknowledgeSetup: () => ipcRenderer.invoke('app:acknowledge-setup'),
  listBackups: () => ipcRenderer.invoke('data:list-backups'),
  createBackup: () => ipcRenderer.invoke('data:create-backup'),
  createExport: () => ipcRenderer.invoke('data:create-export'),
  previewBackup: (id) => ipcRenderer.invoke('data:preview-backup', id),
  selectImport: () => ipcRenderer.invoke('data:select-import'),
  commitImport: (token, confirmation) => ipcRenderer.invoke('data:commit-import', token, confirmation),
  commitRestore: (token, confirmation) => ipcRenderer.invoke('data:commit-restore', token, confirmation),
  getAiDiagnostics: () => ipcRenderer.invoke('ai:diagnostics'),
  proposeCorrection: (learnerText) => ipcRenderer.invoke('ai:propose-correction', learnerText),
  getAudioStatus: () => ipcRenderer.invoke('audio:get-status'),
  setAudioRetention: (retention) => ipcRenderer.invoke('audio:set-retention', retention),
  transcribeSessionAudio: (sessionId, bytes) => ipcRenderer.invoke('audio:transcribe-session', sessionId, bytes),
  submitSessionTranscript: (sessionId, token, transcript) => ipcRenderer.invoke('audio:submit-transcript', sessionId, token, transcript),
  synthesizeSpeech: (text) => ipcRenderer.invoke('audio:synthesize', text),
  startFifteenMinuteSession: () => ipcRenderer.invoke('session:start-fifteen'),
  advanceWarmup: (sessionId) => ipcRenderer.invoke('session:advance-warmup', sessionId),
  submitSessionText: (sessionId, learnerText) => ipcRenderer.invoke('session:submit-text', sessionId, learnerText),
  reviewCorrection: (sessionId, decision) => ipcRenderer.invoke('session:review-correction', sessionId, decision),
  completeFifteenMinuteSession: (sessionId) => ipcRenderer.invoke('session:complete-fifteen', sessionId),
  getWeaknessDetail: (weaknessId) => ipcRenderer.invoke('weakness:get-detail', weaknessId),
  setWeaknessPaused: (weaknessId, paused) => ipcRenderer.invoke('weakness:set-paused', weaknessId, paused),
  startAssessment: (kind) => ipcRenderer.invoke('assessment:start', kind),
  submitAssessmentResponse: (assessmentId, response) => ipcRenderer.invoke('assessment:submit-response', assessmentId, response),
});
